#include<iostream.h>
#include<conio.h>
int main()
{
  clrscr();
  cout.width(12);
  cout<<"Name";
  cout.width(10);
  cout<<"fees";
  cout.width(15);
  cout<<"collage\n";

  cout.width(12);
  cout.fill('#');
  cout<<"Dhiraj";
  cout.width(10);
  cout.precision(5);
  cout.fill('$');
  cout<<22.22552;
  cout.width(15);
  cout.fill('<');
  cout<<"Royal\n";

  cout.width(12);
  cout.fill('#');
  cout<<"Diya";
  cout.width(10);
  cout.precision(5);
  cout.fill('$');
  cout<<22.2355533;
  cout.width(15);
  cout.fill('<');
  cout<<"LDRP\n";

  cout.width(12);
  cout.fill('#');
  cout<<"Yesha";
  cout.width(10);
  cout.precision(5);
  cout.fill('$');
  cout<<22.22444;
  cout.width(15);
  cout.fill('<');
  cout<<"Kadi\n";

  cout.width(12);
  cout.fill('#');
  cout<<"Harit";
  cout.width(10);
  cout.precision(5);
  cout.fill('$');
  cout<<10.00054430;
  cout.width(15);
  cout.fill('<');
  cout<<"PDPU\n";

  cout.width(12);
  cout.fill('#');
  cout<<"Utsav";
  cout.width(10);
  cout.precision(5);
  cout.fill('$');
  cout<<22.2432122;
  cout.width(15);
  cout.fill('<');
  cout<<"pdpu\n";

  getch();
}