/*
		 Author : Yesha
		 DOC: 28/6
		 Object: c

*/
#include<stdio.h>
#include<conio.h>
void main()
{          int a,A ;
	   float b;
	   double c;
	   char ch;
	   long int d;
	   clrscr();


	   printf("\nEnter the value of a as int");
	   scanf("%d",&a);
	   printf("\nEnter the value of A as int");
	   scanf("%d",&A);6


	   printf("\nEnter the value of b as float");
	   scanf("%f",&b);
	   printf("\n


	   printf ("\nEnter the value of c as double \n Enter the value");
	   scanf("%lf",&c);

	   fflush(stdin);

	   printf("\nEnter the value of ch as character");
	   scanf("%c",&ch);

	   printf("\nEnter the value of long int");
	   scanf("%ld",&d);

	   printf("\na =%d",a);

	   printf("\nb =%f",b);

	   printf("\nc =%lf",c);

	   printf("\nch =%c",ch);

	   printf("\nd =%ld",d);


	   getch();
}