#include<iostream.h>
#include<conio.h>
/*
   cout=console output stream
   cout is object

*/
void main()
{
  float no1,no2;
  clrscr();
  cout<<"Enter Number one and number two";
  cin>>no1>>no2;
  cout<<"\nAddition of two number is"<<no1+no2;
  cout<<"\nMultiplication of two number is"<<no1*no2;
  cout<<"\nSubtraction of two number is"<<no1-no2;
  cout<<"\nDivision of two number is"<<no1/no2;

  getch();
}